name: LoginAcess
version: '${project.version}'
main: mc.elderbr.loginacess.LoginAcess
api-version: 1.19
authors: [ ElderBR ]
description: LoginAcess é usado para controlar o acesso ao servidor, podendo adicionar amigo, ajudantes e stream
website: http://elderbr.com/
commands:
  login:
    description: Fazer o login
  cadastro:
    aliases:
      - registro
      - cadastro
      - register
    description: Cadastrar jogador
  addamigo:
    usage: /addamigo <nickplayer>
    description: Adiciona um novo amigo
  removeamigo:
    description: Remover amigo da lista
  addseguidor:
    usage: /addseguidor <nickplayer>
    description: Adiciona um seguidor
  removeseguidor:
    usage: /removeseguidor <nickplayer>
    description: Remove um seguidor da lista e espulsa do servidor
  limparEspera:
    description: Apaga todos os jogadores que estão na fila de espera
  addAdm:
    description: Adicionar administrador do plugin
  removeAdm:
    description: Remover administrador do plugin
  addItem:
    description: Adicionar novo item na lista dos itens negados
  removeItem:
    description: Remover item na lista dos itens negados